export type MainCategory =
  | 'Tops'
  | 'Bottoms'
  | 'Outerwear'
  | 'Shoes'
  | 'Accessories'
  | 'Undergarments'
  | 'Activewear'
  | 'Formalwear';

export type Subcategory =
  | 'T-Shirts'
  | 'Polo Shirts'
  | 'Dress Shirts'
  | 'Henleys'
  | 'Tank Tops'
  | 'Sweaters'
  | 'Hoodies'
  | 'Jeans'
  | 'Chinos'
  | 'Trousers'
  | 'Joggers'
  | 'Shorts'
  | 'Cargo Pants'
  | 'Bomber Jackets'
  | 'Blazers'
  | 'Trench Coats'
  | 'Peacoats'
  | 'Leather Jackets'
  | 'Denim Jackets'
  | 'Parkas'
  | 'Vests'
  | 'Athletic Sneakers'
  | 'Lifestyle Sneakers'
  | 'Oxfords'
  | 'Derbies'
  | 'Monk Straps'
  | 'Loafers'
  | 'Boat Shoes'
  | 'Espadrilles'
  | 'Chelsea Boots'
  | 'Combat Boots'
  | 'Chukkas'
  | 'Sandals'
  | 'Slides'
  | 'Belts'
  | 'Hats'
  | 'Scarves'
  | 'Gloves'
  | 'Sunglasses'
  | 'Watches'
  | 'Jewelry'
  | 'Bags'
  | 'Undershirts'
  | 'Briefs'
  | 'Boxers'
  | 'Socks'
  | 'Athletic Tops'
  | 'Running Shorts'
  | 'Leggings'
  | 'Performance Jackets'
  | 'Gym Hoodies'
  | 'Suits'
  | 'Tuxedos'
  | 'Waistcoats';
