// apps/backend-nest/src/wardrobe/logic/style-agents.ts
import { UserStyle } from './style';

export const STYLE_AGENTS: Record<string, UserStyle> = {
  agent1: {
    name: 'Power Tailoring (Tom Ford–inspired)',
    preferredColors: ['Black', 'Charcoal', 'Navy', 'White'],
    avoidColors: ['Pastel', 'Neon'],
    favoriteBrands: ['Tom Ford', 'Saint Laurent', 'Brioni', 'Zegna'],
    avoidSubcategories: ['Cargo', 'Graphic Tee', 'Distressed Denim'],
    dressBias: 'Business',
    styleKeywords: ['Structured', 'Sharp', 'Glossy', 'Evening'],
    lifestyle: ['Boardroom', 'Gala', 'Cocktail'],
    fashionGoals: ['Command presence with impeccable tailoring'],
    budgetLevel: 2000,
    confidence: 'Very confident',
    climate: 'Temperate',
    bodyType: 'Athletic',
    // new
    topsFit: 'slim',
    bottomsFit: 'slim',
    outerShoulder: 'structured',
    preferredFabrics: ['worsted wool', 'mohair', 'cashmere', 'silk satin'],
    avoidFabrics: ['terry', 'jersey'],
    patternScale: 'micro',
    patternMaxCountPerOutfit: 1,
    palette: {
      base: ['black', 'charcoal', 'navy'],
      accents: ['white', 'silver'],
    },
    contrastTarget: 'high',
    mustPair: { blazer: ['oxfords', 'wholecuts', 'sleek chelsea'] },
    avoidPair: { hoodie: ['sleek dress shoes'] },
    structureBalance: true,
    layerTolerance: 'light',
    footwearLast: 'sleek',
    beltRequiredWhen: 'dress shoes',
    jewelryTolerance: 'minimal',
  },

  agent2: {
    name: 'Minimal Luxe (Phoebe Philo / The Row–inspired)',
    preferredColors: ['Black', 'White', 'Ivory', 'Taupe', 'Grey'],
    avoidColors: ['Neon', 'High Saturation'],
    favoriteBrands: ['The Row', 'Jil Sander', 'Lemaire', 'COS'],
    avoidSubcategories: ['Loud Logos', 'Busy Prints', 'Overly Slim'],
    dressBias: 'BusinessCasual',
    styleKeywords: ['Minimal', 'Quiet Luxury', 'Relaxed Tailoring'],
    lifestyle: ['Work', 'Art Openings', 'Travel'],
    fashionGoals: ['Look effortless and premium'],
    budgetLevel: 1200,
    confidence: 'Calm',
    climate: 'Four Seasons',
    bodyType: 'Slim',
    // new
    topsFit: 'regular',
    bottomsFit: 'straight',
    outerShoulder: 'natural',
    preferredFabrics: ['cashmere', 'silk', 'high-twist wool', 'suede'],
    patternScale: 'none',
    patternMaxCountPerOutfit: 0,
    palette: { base: ['black', 'ivory', 'taupe', 'grey'], accents: ['stone'] },
    contrastTarget: 'low',
    layerTolerance: 'light',
    footwearLast: 'sleek',
    jewelryTolerance: 'minimal',
  },

  agent3: {
    name: 'Heritage Americana (Ralph Lauren–inspired)',
    preferredColors: ['Navy', 'Olive', 'Brown', 'Beige', 'Burgundy'],
    avoidColors: ['Neon', 'Techy Neons'],
    favoriteBrands: ['Ralph Lauren', 'Brooks Brothers', 'Barbour'],
    avoidSubcategories: ['Tech Shells', 'Chunky Logos', 'Hyper-Modern'],
    dressBias: 'SmartCasual',
    styleKeywords: ['Preppy', 'Timeless', 'Ivy', 'Country Club'],
    lifestyle: ['Family Events', 'Travel', 'Fine Dining', 'Golf'],
    fashionGoals: ['Invest in timeless pieces'],
    budgetLevel: 800,
    confidence: 'Conservative',
    climate: 'Four Seasons',
    bodyType: 'Broad',
    // new
    topsFit: 'regular',
    bottomsFit: 'straight',
    preferredFabrics: ['tweed', 'oxford cloth', 'flannel', 'suede'],
    patternScale: 'medium',
    patternMaxCountPerOutfit: 1,
    palette: {
      base: ['navy', 'olive', 'brown'],
      accents: ['cream', 'burgundy'],
    },
    contrastTarget: 'medium',
    mustPair: { sportcoat: ['loafers', 'derbies'] },
    layerTolerance: 'heavy',
    footwearLast: 'round',
    jewelryTolerance: 'minimal',
  },

  agent4: {
    name: 'Rock Slim (Hedi Slimane–inspired)',
    preferredColors: ['Black', 'White', 'Grey'],
    avoidColors: ['Beige', 'Pastel'],
    favoriteBrands: ['Celine', 'Saint Laurent', 'Dior Homme (archive)'],
    avoidSubcategories: ['Relaxed Fit', 'Pleated Wide Trousers'],
    dressBias: 'UltraCasual',
    styleKeywords: ['Slim', 'Rock', 'Monochrome', 'Boots'],
    lifestyle: ['Concerts', 'City Nights'],
    fashionGoals: ['Lean silhouette with attitude'],
    budgetLevel: 1500,
    confidence: 'Very confident',
    climate: 'Urban Cool',
    bodyType: 'Slim',
    // new
    topsFit: 'slim',
    bottomsFit: 'skinny',
    preferredFabrics: ['denim', 'leather', 'wool gabardine'],
    patternScale: 'none',
    patternMaxCountPerOutfit: 0,
    palette: { base: ['black', 'white'], accents: ['silver'] },
    contrastTarget: 'high',
    mustPair: { leather_jacket: ['boots'] },
    avoidPair: { hoodie: ['sleek dress shoes'] },
    layerTolerance: 'light',
    footwearLast: 'sleek',
    jewelryTolerance: 'statement',
  },

  agent5: {
    name: 'Quiet Cashmere (Brunello Cucinelli–inspired)',
    preferredColors: ['Taupe', 'Ivory', 'Stone', 'Brown', 'Soft Blue'],
    avoidColors: ['Neon', 'High Contrast'],
    favoriteBrands: ['Brunello Cucinelli', 'Loro Piana', 'Zegna'],
    avoidSubcategories: ['Loud Logos', 'Synthetic Shine'],
    dressBias: 'SmartCasual',
    styleKeywords: ['Soft Tailoring', 'Tonal', 'Cashmere', 'Suede'],
    lifestyle: ['Business Travel', 'Weekend', 'Lunch Meetings'],
    fashionGoals: ['Look refined yet relaxed'],
    budgetLevel: 2500,
    confidence: 'Assured',
    climate: 'Mild',
    bodyType: 'Athletic',
    // new
    topsFit: 'regular',
    bottomsFit: 'slim',
    outerShoulder: 'soft',
    preferredFabrics: ['cashmere', 'suede', 'flannel', 'silk-cashmere'],
    patternScale: 'micro',
    patternMaxCountPerOutfit: 1,
    palette: { base: ['taupe', 'ivory', 'stone'], accents: ['soft blue'] },
    contrastTarget: 'low',
    layerTolerance: 'light',
    footwearLast: 'round',
    jewelryTolerance: 'minimal',
  },

  agent6: {
    name: 'Avant-Garde Monochrome (Rick Owens–inspired)',
    preferredColors: ['Black', 'Charcoal', 'Bone'],
    avoidColors: ['Primary Colors', 'Pastel'],
    favoriteBrands: ['Rick Owens', 'Guidi', 'Ann Demeulemeester'],
    avoidSubcategories: ['Classic Prep', 'Heritage Plaids'],
    dressBias: 'UltraCasual',
    styleKeywords: ['Draped', 'Stacked', 'Geometric', 'Edgy'],
    lifestyle: ['Art Shows', 'Nightlife'],
    fashionGoals: ['Architectural silhouettes with drama'],
    budgetLevel: 1200,
    confidence: 'Experimental',
    climate: 'Temperate',
    bodyType: 'Slim',
    // new
    topsFit: 'relaxed',
    bottomsFit: 'slim',
    preferredFabrics: ['jersey', 'leather', 'cashmere', 'technical nylon'],
    patternScale: 'none',
    patternMaxCountPerOutfit: 0,
    palette: { base: ['black', 'charcoal'], accents: ['bone'] },
    contrastTarget: 'medium',
    mustPair: { longline_top: ['chunky boots'] },
    avoidPair: { blazer: ['sneakers with loud logos'] },
    structureBalance: false,
    layerTolerance: 'heavy',
    footwearLast: 'chunky',
    jewelryTolerance: 'statement',
  },

  agent7: {
    name: 'Street Luxury (Virgil Abloh–inspired)',
    preferredColors: ['Black', 'White', 'Red', 'Volt'],
    avoidColors: ['Beige-only Fits'],
    favoriteBrands: ['Off-White', 'Nike', 'Louis Vuitton (mens)'],
    avoidSubcategories: ['Classic Suiting', 'Loafers'],
    dressBias: 'Casual',
    styleKeywords: ['Statement', 'Graphic', 'Deconstructed'],
    lifestyle: ['City', 'Concerts', 'Sneaker Drops'],
    fashionGoals: ['Stand out with culture-first pieces'],
    budgetLevel: 900,
    confidence: 'Bold',
    climate: 'Urban Cool',
    bodyType: 'Athletic',
    // new
    topsFit: 'boxy',
    bottomsFit: 'straight',
    preferredFabrics: ['denim', 'cotton jersey', 'nylon'],
    patternScale: 'bold',
    patternMaxCountPerOutfit: 1,
    palette: { base: ['black', 'white'], accents: ['red', 'volt'] },
    contrastTarget: 'high',
    mustPair: { hoodie: ['sneakers'] },
    avoidPair: { blazer: ['sleek oxfords'] },
    layerTolerance: 'light',
    footwearLast: 'round',
    jewelryTolerance: 'statement',
  },

  agent8: {
    name: 'Soft Italian Sprezzatura',
    preferredColors: ['Navy', 'Brown', 'Olive', 'Cream'],
    avoidColors: ['Neon', 'Harsh Black Head-to-Toe'],
    favoriteBrands: ['Isaia', 'Canali', 'Pini Parma', 'Caruso'],
    avoidSubcategories: ['Boxy Jackets', 'Square-Toe Shoes'],
    dressBias: 'BusinessCasual',
    styleKeywords: ['Unstructured', 'High-Twist Wool', 'Sprezzatura'],
    lifestyle: ['Aperitivo', 'Work', 'Weddings'],
    fashionGoals: ['Tailored yet comfortable'],
    budgetLevel: 1200,
    confidence: 'Confident',
    climate: 'Mediterranean',
    bodyType: 'Athletic',
    // new
    topsFit: 'regular',
    bottomsFit: 'slim',
    outerShoulder: 'natural',
    preferredFabrics: ['high-twist wool', 'linen', 'cotton twill'],
    patternScale: 'micro',
    patternMaxCountPerOutfit: 1,
    palette: { base: ['navy', 'brown', 'olive'], accents: ['cream'] },
    contrastTarget: 'medium',
    mustPair: { sportcoat: ['loafers'] },
    layerTolerance: 'light',
    footwearLast: 'sleek',
    jewelryTolerance: 'minimal',
  },

  agent9: {
    name: 'Sport-Tech Urban (Acronym/Stone Island–inspired)',
    preferredColors: ['Black', 'Olive', 'Charcoal', 'Navy'],
    avoidColors: ['Pastel', 'Beige Suiting'],
    favoriteBrands: [
      'Acronym',
      'Stone Island',
      'Nike ACG',
      'Arc’teryx Veilance',
    ],
    avoidSubcategories: ['Heritage Tweed', 'Dress Oxfords'],
    dressBias: 'Casual',
    styleKeywords: ['Technical', 'Layered', 'Utility', 'Weatherproof'],
    lifestyle: ['Commute', 'Travel', 'Weekend'],
    fashionGoals: ['Function-first performance with edge'],
    budgetLevel: 700,
    confidence: 'Practical',
    climate: 'Rainy',
    bodyType: 'Athletic',
    // new
    topsFit: 'regular',
    bottomsFit: 'slim',
    preferredFabrics: ['gore-tex', 'nylon', 'softshell'],
    patternScale: 'none',
    patternMaxCountPerOutfit: 0,
    palette: {
      base: ['black', 'olive', 'charcoal'],
      accents: ['safety green'],
    },
    contrastTarget: 'medium',
    mustPair: { shell: ['sneakers'] },
    avoidPair: { sport_coat: ['dress shoes'] },
    layerTolerance: 'heavy',
    footwearLast: 'round',
    jewelryTolerance: 'none',
  },

  agent10: {
    name: 'Modern Business Casual (Theory/COS–inspired)',
    preferredColors: ['Navy', 'Grey', 'Black', 'White', 'Stone'],
    avoidColors: ['Neon', 'Loud Prints'],
    favoriteBrands: ['Theory', 'COS', 'Suitsupply', 'Eton'],
    avoidSubcategories: ['Cargo', 'Baggy', 'Distressed'],
    dressBias: 'BusinessCasual',
    styleKeywords: ['Clean', 'Tailored', 'Office-Ready'],
    lifestyle: ['Work', 'Networking'],
    fashionGoals: ['Polished without being formal'],
    budgetLevel: 600,
    confidence: 'Assured',
    climate: 'Four Seasons',
    bodyType: 'Average',
    // new
    topsFit: 'regular',
    bottomsFit: 'slim',
    outerShoulder: 'natural',
    preferredFabrics: ['wool', 'cotton', 'merino'],
    patternScale: 'micro',
    patternMaxCountPerOutfit: 1,
    palette: { base: ['navy', 'grey', 'stone'], accents: ['white', 'black'] },
    contrastTarget: 'medium',
    mustPair: { sportcoat: ['derbies', 'loafers'] },
    layerTolerance: 'light',
    footwearLast: 'sleek',
    jewelryTolerance: 'minimal',
  },

  agent11: {
    name: 'Mediterranean Linen (Resort Smart)',
    preferredColors: ['Ivory', 'Beige', 'Sage', 'Light Blue', 'Tobacco'],
    avoidColors: ['Black Head-to-Toe'],
    favoriteBrands: ['Loro Piana', 'Orlebar Brown', 'Sunspel'],
    avoidSubcategories: ['Heavy Tweed', 'Bulky Parkas'],
    dressBias: 'SmartCasual',
    styleKeywords: ['Breathable', 'Linen', 'Resort', 'Relaxed'],
    lifestyle: ['Resorts', 'Coastal Dinners', 'Travel'],
    fashionGoals: ['Airy, elegant warm-weather looks'],
    budgetLevel: 1100,
    confidence: 'Calm',
    climate: 'Warm',
    bodyType: 'Athletic',
    // new
    topsFit: 'regular',
    bottomsFit: 'straight',
    preferredFabrics: ['linen', 'silk', 'cotton poplin'],
    patternScale: 'micro',
    patternMaxCountPerOutfit: 1,
    palette: {
      base: ['ivory', 'beige', 'light blue'],
      accents: ['tobacco', 'sage'],
    },
    contrastTarget: 'low',
    layerTolerance: 'light',
    footwearLast: 'round',
    jewelryTolerance: 'minimal',
  },

  agent12: {
    name: 'Editorial Classic (Magazine Stylist–inspired)',
    preferredColors: ['Navy', 'Camel', 'Black', 'White'],
    avoidColors: ['Neon'],
    favoriteBrands: ['Prada', 'Bottega Veneta', 'Gucci', 'Hermès'],
    avoidSubcategories: ['Overly Sporty', 'Logo-Heavy Streetwear'],
    dressBias: 'Business',
    styleKeywords: ['Iconic', 'Curated', 'Photogenic', 'Balanced'],
    lifestyle: ['Press Events', 'Openings', 'Formal Dinners'],
    fashionGoals: ['Classic with a modern twist'],
    budgetLevel: 1800,
    confidence: 'Very confident',
    climate: 'Four Seasons',
    bodyType: 'Slim',
    // new
    topsFit: 'slim',
    bottomsFit: 'slim',
    outerShoulder: 'structured',
    preferredFabrics: ['wool', 'silk', 'cashmere'],
    patternScale: 'micro',
    patternMaxCountPerOutfit: 1,
    palette: { base: ['navy', 'camel', 'black'], accents: ['white'] },
    contrastTarget: 'medium',
    mustPair: { blazer: ['oxfords', 'loafers'] },
    avoidPair: { hoodie: ['dress shoes'] },
    layerTolerance: 'light',
    footwearLast: 'sleek',
    jewelryTolerance: 'minimal',
  },
};

//////////////////

// import { UserStyle } from './style';

// export const STYLE_AGENTS: Record<string, UserStyle> = {
//   agent1: {
//     name: 'Power Tailoring (Tom Ford–inspired)',
//     preferredColors: ['Black', 'Charcoal', 'Navy', 'White'],
//     avoidColors: ['Pastel', 'Neon'],
//     favoriteBrands: ['Tom Ford', 'Saint Laurent', 'Brioni', 'Zegna'],
//     avoidSubcategories: ['Cargo', 'Graphic Tee', 'Distressed Denim'],
//     dressBias: 'Business',
//     styleKeywords: ['Structured', 'Sharp', 'Glossy', 'Evening'],
//     lifestyle: ['Boardroom', 'Gala', 'Cocktail'],
//     fashionGoals: ['Command presence with impeccable tailoring'],
//     budgetLevel: 2000,
//     confidence: 'Very confident',
//     climate: 'Temperate',
//     bodyType: 'Athletic',
//   },

//   agent2: {
//     name: 'Minimal Luxe (Phoebe Philo / The Row–inspired)',
//     preferredColors: ['Black', 'White', 'Ivory', 'Taupe', 'Grey'],
//     avoidColors: ['Neon', 'High Saturation'],
//     favoriteBrands: ['The Row', 'Jil Sander', 'Lemaire', 'COS'],
//     avoidSubcategories: ['Loud Logos', 'Busy Prints', 'Overly Slim'],
//     dressBias: 'BusinessCasual',
//     styleKeywords: ['Minimal', 'Quiet Luxury', 'Relaxed Tailoring'],
//     lifestyle: ['Work', 'Art Openings', 'Travel'],
//     fashionGoals: ['Look effortless and premium'],
//     budgetLevel: 1200,
//     confidence: 'Calm',
//     climate: 'Four Seasons',
//     bodyType: 'Slim',
//   },

//   agent3: {
//     name: 'Heritage Americana (Ralph Lauren–inspired)',
//     preferredColors: ['Navy', 'Olive', 'Brown', 'Beige', 'Burgundy'],
//     avoidColors: ['Neon', 'Techy Neons'],
//     favoriteBrands: ['Ralph Lauren', 'Brooks Brothers', 'Barbour'],
//     avoidSubcategories: ['Tech Shells', 'Chunky Logos', 'Hyper-Modern'],
//     dressBias: 'SmartCasual',
//     styleKeywords: ['Preppy', 'Timeless', 'Ivy', 'Country Club'],
//     lifestyle: ['Family Events', 'Travel', 'Fine Dining', 'Golf'],
//     fashionGoals: ['Invest in timeless pieces'],
//     budgetLevel: 800,
//     confidence: 'Conservative',
//     climate: 'Four Seasons',
//     bodyType: 'Broad',
//   },

//   agent4: {
//     name: 'Rock Slim (Hedi Slimane–inspired)',
//     preferredColors: ['Black', 'White', 'Grey'],
//     avoidColors: ['Beige', 'Pastel'],
//     favoriteBrands: ['Celine', 'Saint Laurent', 'Dior Homme (archive)'],
//     avoidSubcategories: ['Relaxed Fit', 'Pleated Wide Trousers'],
//     dressBias: 'UltraCasual',
//     styleKeywords: ['Slim', 'Rock', 'Monochrome', 'Boots'],
//     lifestyle: ['Concerts', 'City Nights'],
//     fashionGoals: ['Lean silhouette with attitude'],
//     budgetLevel: 1500,
//     confidence: 'Very confident',
//     climate: 'Urban Cool',
//     bodyType: 'Slim',
//   },

//   agent5: {
//     name: 'Quiet Cashmere (Brunello Cucinelli–inspired)',
//     preferredColors: ['Taupe', 'Ivory', 'Stone', 'Brown', 'Soft Blue'],
//     avoidColors: ['Neon', 'High Contrast'],
//     favoriteBrands: ['Brunello Cucinelli', 'Loro Piana', 'Zegna'],
//     avoidSubcategories: ['Loud Logos', 'Synthetic Shine'],
//     dressBias: 'SmartCasual',
//     styleKeywords: ['Soft Tailoring', 'Tonal', 'Cashmere', 'Suede'],
//     lifestyle: ['Business Travel', 'Weekend', 'Lunch Meetings'],
//     fashionGoals: ['Look refined yet relaxed'],
//     budgetLevel: 2500,
//     confidence: 'Assured',
//     climate: 'Mild',
//     bodyType: 'Athletic',
//   },

//   agent6: {
//     name: 'Avant-Garde Monochrome (Rick Owens–inspired)',
//     preferredColors: ['Black', 'Charcoal', 'Bone'],
//     avoidColors: ['Primary Colors', 'Pastel'],
//     favoriteBrands: ['Rick Owens', 'Guidi', 'Ann Demeulemeester'],
//     avoidSubcategories: ['Classic Prep', 'Heritage Plaids'],
//     dressBias: 'UltraCasual',
//     styleKeywords: ['Draped', 'Stacked', 'Geometric', 'Edgy'],
//     lifestyle: ['Art Shows', 'Nightlife'],
//     fashionGoals: ['Architectural silhouettes with drama'],
//     budgetLevel: 1200,
//     confidence: 'Experimental',
//     climate: 'Temperate',
//     bodyType: 'Slim',
//   },

//   agent7: {
//     name: 'Street Luxury (Virgil Abloh–inspired)',
//     preferredColors: ['Black', 'White', 'Red', 'Volt'],
//     avoidColors: ['Beige-only Fits'],
//     favoriteBrands: ['Off-White', 'Nike', 'Louis Vuitton (mens)'],
//     avoidSubcategories: ['Classic Suiting', 'Loafers'],
//     dressBias: 'Casual',
//     styleKeywords: ['Statement', 'Graphic', 'Deconstructed'],
//     lifestyle: ['City', 'Concerts', 'Sneaker Drops'],
//     fashionGoals: ['Stand out with culture-first pieces'],
//     budgetLevel: 900,
//     confidence: 'Bold',
//     climate: 'Urban Cool',
//     bodyType: 'Athletic',
//   },

//   agent8: {
//     name: 'Soft Italian Sprezzatura',
//     preferredColors: ['Navy', 'Brown', 'Olive', 'Cream'],
//     avoidColors: ['Neon', 'Harsh Black Head-to-Toe'],
//     favoriteBrands: ['Isaia', 'Canali', 'Pini Parma', 'Caruso'],
//     avoidSubcategories: ['Boxy Jackets', 'Square-Toe Shoes'],
//     dressBias: 'BusinessCasual',
//     styleKeywords: ['Unstructured', 'High-Twist Wool', 'Sprezzatura'],
//     lifestyle: ['Aperitivo', 'Work', 'Weddings'],
//     fashionGoals: ['Tailored yet comfortable'],
//     budgetLevel: 1200,
//     confidence: 'Confident',
//     climate: 'Mediterranean',
//     bodyType: 'Athletic',
//   },

//   agent9: {
//     name: 'Sport-Tech Urban (Acronym/Stone Island–inspired)',
//     preferredColors: ['Black', 'Olive', 'Charcoal', 'Navy'],
//     avoidColors: ['Pastel', 'Beige Suiting'],
//     favoriteBrands: [
//       'Acronym',
//       'Stone Island',
//       'Nike ACG',
//       'Arc’teryx Veilance',
//     ],
//     avoidSubcategories: ['Heritage Tweed', 'Dress Oxfords'],
//     dressBias: 'Casual',
//     styleKeywords: ['Technical', 'Layered', 'Utility', 'Weatherproof'],
//     lifestyle: ['Commute', 'Travel', 'Weekend'],
//     fashionGoals: ['Function-first performance with edge'],
//     budgetLevel: 700,
//     confidence: 'Practical',
//     climate: 'Rainy',
//     bodyType: 'Athletic',
//   },

//   agent10: {
//     name: 'Modern Business Casual (Theory/COS–inspired)',
//     preferredColors: ['Navy', 'Grey', 'Black', 'White', 'Stone'],
//     avoidColors: ['Neon', 'Loud Prints'],
//     favoriteBrands: ['Theory', 'COS', 'Suitsupply', 'Eton'],
//     avoidSubcategories: ['Cargo', 'Baggy', 'Distressed'],
//     dressBias: 'BusinessCasual',
//     styleKeywords: ['Clean', 'Tailored', 'Office-Ready'],
//     lifestyle: ['Work', 'Networking'],
//     fashionGoals: ['Polished without being formal'],
//     budgetLevel: 600,
//     confidence: 'Assured',
//     climate: 'Four Seasons',
//     bodyType: 'Average',
//   },

//   agent11: {
//     name: 'Mediterranean Linen (Resort Smart)',
//     preferredColors: ['Ivory', 'Beige', 'Sage', 'Light Blue', 'Tobacco'],
//     avoidColors: ['Black Head-to-Toe'],
//     favoriteBrands: ['Loro Piana', 'Orlebar Brown', 'Sunspel'],
//     avoidSubcategories: ['Heavy Tweed', 'Bulky Parkas'],
//     dressBias: 'SmartCasual',
//     styleKeywords: ['Breathable', 'Linen', 'Resort', 'Relaxed'],
//     lifestyle: ['Resorts', 'Coastal Dinners', 'Travel'],
//     fashionGoals: ['Airy, elegant warm-weather looks'],
//     budgetLevel: 1100,
//     confidence: 'Calm',
//     climate: 'Warm',
//     bodyType: 'Athletic',
//   },

//   agent12: {
//     name: 'Editorial Classic (Magazine Stylist–inspired)',
//     preferredColors: ['Navy', 'Camel', 'Black', 'White'],
//     avoidColors: ['Neon'],
//     favoriteBrands: ['Prada', 'Bottega Veneta', 'Gucci', 'Hermès'],
//     avoidSubcategories: ['Overly Sporty', 'Logo-Heavy Streetwear'],
//     dressBias: 'Business',
//     styleKeywords: ['Iconic', 'Curated', 'Photogenic', 'Balanced'],
//     lifestyle: ['Press Events', 'Openings', 'Formal Dinners'],
//     fashionGoals: ['Classic with a modern twist'],
//     budgetLevel: 1800,
//     confidence: 'Very confident',
//     climate: 'Four Seasons',
//     bodyType: 'Slim',
//   },
// };

//////////////

// import { UserStyle } from './style';

// export const STYLE_AGENTS: Record<string, UserStyle> = {
//   agent1: {
//     name: 'Pro Stylist – Clean Minimal',
//     preferredColors: ['Black', 'White', 'Gray'],
//     avoidColors: ['Brights', 'Patterns'],
//     favoriteBrands: ['Theory', 'Eton', 'Jil Sander'],
//     avoidSubcategories: ['Baggy', 'Graphic Tee', 'Cargo'],
//     dressBias: 'BusinessCasual',
//     styleKeywords: ['Minimal', 'Tailored', 'Polished', 'Understated'],
//     lifestyle: ['Work', 'Networking', 'Formal Events'],
//     fashionGoals: ['Always look sharp and professional'],
//     budgetLevel: 800,
//     confidence: 'Very confident',
//     climate: 'Temperate',
//     bodyType: 'Slim',
//   },

//   agent2: {
//     name: 'Rebel Streetwear',
//     preferredColors: ['Black', 'Red', 'Neon'],
//     avoidColors: ['Beige', 'Pastel'],
//     favoriteBrands: ['Amiri', 'Off-White', 'Nike', 'Supreme'],
//     avoidSubcategories: ['Dress Shirt', 'Loafers', 'Suit'],
//     dressBias: 'UltraCasual',
//     styleKeywords: ['Bold', 'Youthful', 'Oversized', 'Statement'],
//     lifestyle: ['City Nights', 'Concerts', 'Skate Parks'],
//     fashionGoals: ['Stand out, break rules'],
//     budgetLevel: 300,
//     confidence: 'Experimental',
//     climate: 'Urban Cool',
//     bodyType: 'Athletic',
//   },

//   agent3: {
//     name: 'Classic Heritage Gentleman',
//     preferredColors: ['Brown', 'Olive', 'Navy', 'Beige'],
//     avoidColors: ['Neon', 'Black'],
//     favoriteBrands: ['Burberry', 'Ralph Lauren', 'Brooks Brothers'],
//     avoidSubcategories: ['Sneakers', 'Hoodies', 'Cargo'],
//     dressBias: 'SmartCasual',
//     styleKeywords: ['Traditional', 'Timeless', 'Elegant', 'Country Club'],
//     lifestyle: ['Travel', 'Golf', 'Fine Dining', 'Family Events'],
//     fashionGoals: ['Invest in timeless pieces'],
//     budgetLevel: 1000,
//     confidence: 'Conservative',
//     climate: 'Four Seasons',
//     bodyType: 'Broad',
//   },
//   agent4: {
//     name: 'Classic Heritage Gentleman',
//     preferredColors: ['Brown', 'Olive', 'Navy', 'Beige'],
//     avoidColors: ['Neon', 'Black'],
//     favoriteBrands: ['Burberry', 'Ralph Lauren', 'Brooks Brothers'],
//     avoidSubcategories: ['Sneakers', 'Hoodies', 'Cargo'],
//     dressBias: 'SmartCasual',
//     styleKeywords: ['Traditional', 'Timeless', 'Elegant', 'Country Club'],
//     lifestyle: ['Travel', 'Golf', 'Fine Dining', 'Family Events'],
//     fashionGoals: ['Invest in timeless pieces'],
//     budgetLevel: 1000,
//     confidence: 'Conservative',
//     climate: 'Four Seasons',
//     bodyType: 'Broad',
//   },
//   agent5: {
//     name: 'Classic Heritage Gentleman',
//     preferredColors: ['Brown', 'Olive', 'Navy', 'Beige'],
//     avoidColors: ['Neon', 'Black'],
//     favoriteBrands: ['Burberry', 'Ralph Lauren', 'Brooks Brothers'],
//     avoidSubcategories: ['Sneakers', 'Hoodies', 'Cargo'],
//     dressBias: 'SmartCasual',
//     styleKeywords: ['Traditional', 'Timeless', 'Elegant', 'Country Club'],
//     lifestyle: ['Travel', 'Golf', 'Fine Dining', 'Family Events'],
//     fashionGoals: ['Invest in timeless pieces'],
//     budgetLevel: 1000,
//     confidence: 'Conservative',
//     climate: 'Four Seasons',
//     bodyType: 'Broad',
//   },
//   agent6: {
//     name: 'Classic Heritage Gentleman',
//     preferredColors: ['Brown', 'Olive', 'Navy', 'Beige'],
//     avoidColors: ['Neon', 'Black'],
//     favoriteBrands: ['Burberry', 'Ralph Lauren', 'Brooks Brothers'],
//     avoidSubcategories: ['Sneakers', 'Hoodies', 'Cargo'],
//     dressBias: 'SmartCasual',
//     styleKeywords: ['Traditional', 'Timeless', 'Elegant', 'Country Club'],
//     lifestyle: ['Travel', 'Golf', 'Fine Dining', 'Family Events'],
//     fashionGoals: ['Invest in timeless pieces'],
//     budgetLevel: 1000,
//     confidence: 'Conservative',
//     climate: 'Four Seasons',
//     bodyType: 'Broad',
//   },
//   agent7: {
//     name: 'Classic Heritage Gentleman',
//     preferredColors: ['Brown', 'Olive', 'Navy', 'Beige'],
//     avoidColors: ['Neon', 'Black'],
//     favoriteBrands: ['Burberry', 'Ralph Lauren', 'Brooks Brothers'],
//     avoidSubcategories: ['Sneakers', 'Hoodies', 'Cargo'],
//     dressBias: 'SmartCasual',
//     styleKeywords: ['Traditional', 'Timeless', 'Elegant', 'Country Club'],
//     lifestyle: ['Travel', 'Golf', 'Fine Dining', 'Family Events'],
//     fashionGoals: ['Invest in timeless pieces'],
//     budgetLevel: 1000,
//     confidence: 'Conservative',
//     climate: 'Four Seasons',
//     bodyType: 'Broad',
//   },
//   agent8: {
//     name: 'Classic Heritage Gentleman',
//     preferredColors: ['Brown', 'Olive', 'Navy', 'Beige'],
//     avoidColors: ['Neon', 'Black'],
//     favoriteBrands: ['Burberry', 'Ralph Lauren', 'Brooks Brothers'],
//     avoidSubcategories: ['Sneakers', 'Hoodies', 'Cargo'],
//     dressBias: 'SmartCasual',
//     styleKeywords: ['Traditional', 'Timeless', 'Elegant', 'Country Club'],
//     lifestyle: ['Travel', 'Golf', 'Fine Dining', 'Family Events'],
//     fashionGoals: ['Invest in timeless pieces'],
//     budgetLevel: 1000,
//     confidence: 'Conservative',
//     climate: 'Four Seasons',
//     bodyType: 'Broad',
//   },
//   agent9: {
//     name: 'Classic Heritage Gentleman',
//     preferredColors: ['Brown', 'Olive', 'Navy', 'Beige'],
//     avoidColors: ['Neon', 'Black'],
//     favoriteBrands: ['Burberry', 'Ralph Lauren', 'Brooks Brothers'],
//     avoidSubcategories: ['Sneakers', 'Hoodies', 'Cargo'],
//     dressBias: 'SmartCasual',
//     styleKeywords: ['Traditional', 'Timeless', 'Elegant', 'Country Club'],
//     lifestyle: ['Travel', 'Golf', 'Fine Dining', 'Family Events'],
//     fashionGoals: ['Invest in timeless pieces'],
//     budgetLevel: 1000,
//     confidence: 'Conservative',
//     climate: 'Four Seasons',
//     bodyType: 'Broad',
//   },
//   agent10: {
//     name: 'Classic Heritage Gentleman',
//     preferredColors: ['Brown', 'Olive', 'Navy', 'Beige'],
//     avoidColors: ['Neon', 'Black'],
//     favoriteBrands: ['Burberry', 'Ralph Lauren', 'Brooks Brothers'],
//     avoidSubcategories: ['Sneakers', 'Hoodies', 'Cargo'],
//     dressBias: 'SmartCasual',
//     styleKeywords: ['Traditional', 'Timeless', 'Elegant', 'Country Club'],
//     lifestyle: ['Travel', 'Golf', 'Fine Dining', 'Family Events'],
//     fashionGoals: ['Invest in timeless pieces'],
//     budgetLevel: 1000,
//     confidence: 'Conservative',
//     climate: 'Four Seasons',
//     bodyType: 'Broad',
//   },
// };
