require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.4'
install! 'cocoapods', deterministic_uuids: false

target 'StylIQ' do
  config = use_native_modules!()
  ENV['RCT_NO_LAUNCH_PACKAGER'] = 'true'

  flags = get_default_flags()

  use_react_native!(
    path: config[:reactNativePath],
    hermes_enabled: true,
    fabric_enabled: flags[:fabric_enabled],
    flipper_configuration: FlipperConfiguration.disabled,
    app_path: "#{Pod::Config.instance.installation_root}/.."
  )

  # react-native-maps
  pod 'react-native-maps', path: '../node_modules/react-native-maps'

  # react-native-permissions
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"
  pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone"

  # react-native-voice
  pod 'react-native-voice', path: '../node_modules/@react-native-voice/voice'

  target 'StylIQTests' do
    inherit! :complete
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      mac_catalyst_enabled: false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)

    # ⬇️ Force iOS deployment target for all pods
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.4'
      end
    end
  end
end
